version: "3.9"

services:

  web:
    build:
      context: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000 &&
             python manage.py migrate"
    volumes:
      - ./limit_book:/limit_book
    env_file:
      - ./.env
    ports:
      - "8000:8000"

  rabbitmq:
    image: rabbitmq:3.12-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  celery:
    restart: always
    build:
      context: .
    command: celery -A limit_book worker -l info
    volumes:
      - ./limit_book:/limit_book
    container_name: celery
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
      - web
